<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'normal',
);
## END OF AUTOGENERATED OPTIONS

return array (
    array (
        'label' => 'Beranda',
        'icon' => '',
        'url' => 'admin/beranda',
        'formattedUrl' => '/index.php?r=admin/beranda',
    ),
    array (
        'label' => 'Master',
        'icon' => '',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'Jenis Hambatan',
                'icon' => '',
                'url' => 'admin/mJenisHambatan',
                'formattedUrl' => '/index.php?r=admin/mJenisHambatan',
            ),
            array (
                'label' => 'Hambatan',
                'icon' => '',
                'url' => 'admin/mHambatan',
                'formattedUrl' => '/index.php?r=admin/mHambatan',
            ),
            array (
                'label' => 'Matriks Perencanaan',
                'icon' => '',
                'url' => 'admin/matriksPerencanaan',
            ),
            array (
                'label' => 'Kurikulum',
                'icon' => '',
                'url' => 'admin/kurikulum',
                'formattedUrl' => '/index.php?r=admin/kurikulum',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Tahun Ajar',
                'icon' => '',
                'url' => 'admin/mTahunAjar',
                'formattedUrl' => '/index.php?r=admin/mTahunAjar',
            ),
            array (
                'label' => 'Jenis Layanan',
                'icon' => '',
                'url' => 'admin/mJenisLayanan',
                'formattedUrl' => '/index.php?r=admin/mJenisLayanan',
            ),
            array (
                'label' => 'Assessment',
                'icon' => '',
                'url' => 'admin/mAssessment',
                'formattedUrl' => '/index.php?r=admin/mAssessment',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Jabatan',
                'icon' => '',
                'url' => 'admin/mJabatan',
                'formattedUrl' => '/index.php?r=admin/mJabatan',
            ),
            array (
                'label' => 'Agama',
                'icon' => '',
                'url' => 'admin/mAgama',
                'formattedUrl' => '/index.php?r=admin/mAgama',
            ),
            array (
                'label' => 'Jenis Kelamin',
                'icon' => '',
                'url' => 'admin/mJenisKelamin',
                'formattedUrl' => '/index.php?r=admin/mJenisKelamin',
            ),
        ),
        'state' => 'collapsed',
    ),
    array (
        'label' => 'User',
        'icon' => '',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'Admin',
                'icon' => '',
                'url' => 'admin/admin',
                'formattedUrl' => '/index.php?r=admin/admin',
            ),
            array (
                'label' => 'Pegawai',
                'icon' => '',
                'url' => 'admin/pegawai',
                'formattedUrl' => '/index.php?r=admin/pegawai',
            ),
            array (
                'label' => 'Orang Tua',
                'icon' => '',
                'url' => '#',
            ),
        ),
        'state' => 'collapsed',
    ),
);